swagger: '2.0'
info:
  version: 1.3.3
  title: TomoX Relayer APIs
  description: Happy to code TomoX Relayer APIs
  license:
    name: Github
    url: 'https://github.com/tomochain/tomox-relayer-apis'
tags:
  - name: Config
    description: Get Application Configuration
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/config:
    get:
      tags:
        - Config
      summary: Get TomoMaster Application Configuration
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/config'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '406':
          description: Not Acceptable
        '500':
          description: Server Internal Error
